spring.application.name=astronova-website-backend

# Active Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

# Server Port
server.port=${PORT:8080}

# Upload
file.upload-dir=${UPLOAD_DIR:/app/uploads}

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Admin
astronova.admin.email=${ADMIN_EMAIL}