# Database
spring.datasource.url=${MySQL.MYSQL_URL}
spring.datasource.username=${MySQL.MYSQLUSER}
spring.datasource.password=${MySQL.MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false   

# Server
server.port=${PORT}

# Mail
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Admin Email
astronova.admin.email=${ADMIN_EMAIL}
