# Test Database
spring.datasource.url=jdbc:mysql://localhost:3306/astronova_test
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Server
server.port=2027

# Mail
spring.mail.username=test@example.com
spring.mail.password=test-password

# Admin Email
astronova.admin.email=test@example.com